#!/bin/bash

export VERBOSE=0
source ./simple_curses.sh

which adb

export HEXAGON_ROOT=$HOME/Qualcomm/Hexagon_SDK/4.5.0.3
export MINIDM_PATH=${HEXAGON_ROOT}/tools/debug/mini-dm/Ubuntu18/mini-dm
export DEVICE_SERIAL=''

export target_cpu_debug_path='/sys/devices/system/cpu'

function init() {

    echo '(II) Checking Hexagon root folder'
    if [ -d "$HEXAGON_ROOT" ];
    then
        echo "(II) $HEXAGON_ROOT directory exists."
    else
	    echo "(EE) $HEXAGON_ROOT directory does not exist."
        exit
    fi
    
    adb devices
    read -p "(==) Enter ADB device serial (Enter): " DEVICE_SERIAL

    echo '(**) Mount debug partition'
    adb -s ${DEVICE_SERIAL} wait-for-device root
    adb -s ${DEVICE_SERIAL} wait-for-device remount
    adb -s ${DEVICE_SERIAL} wait-for-device root
    adb -s ${DEVICE_SERIAL} shell mount -t debugfs none /sys/kernel/debug
    echo '(**) Debug mounted...'

    get_adb_devices
    get_minidm_devices
    get_qrb5165_cpu_clk_max
    get_qrb5165_cpu_clk_min
    get_qrb5165_gpu_clk_max
    get_qrb5165_gpu_clk_min
    get_system_info
}

function get_adb_devices() {
    adb devices | tail -n +2 | tr -d '\tdevices' | head --lines=-1 > /tmp/sample_qtop_adb_devices.log
}

function get_minidm_devices() {
    $MINIDM_PATH --devices | tail -n +4 > /tmp/sample_qtop_minidm_devices.log
    mdev=$($MINIDM_PATH --devices)
    export minidm_first_usbport=${mdev#*USB Port: }
    $MINIDM_PATH --usbport $minidm_first_usbport --msg-file /tmp/sample_qtop_minidm.log --filter_in "CDSP" > /tmp/sample_qtop_minidm_status.log &
}
trap 'trap - SIGTERM && kill 0' SIGINT SIGTERM EXIT

function get_minidm_logs() {
    lines=5
    tail -n$lines /tmp/sample_qtop_minidm.log > /tmp/sample_qtop_minidm_log_lines.log
}

function get_qrb5165_cpu_clk_max() {

    scale=2
    pre=1000000

    # Kyro 585 Prime @ 2.84GHz
    export cpu_clk_cpu0_max=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu7/cpufreq/scaling_max_freq | tr -d '\r\n')
    export cpu_clk_cpu0_max_format=$(bc <<< "scale=$scale; $cpu_clk_cpu0_max / $pre")

    # Kyro 585 Gold @ 2.42GHz
    export cpu_clk_cpu1_max=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu4/cpufreq/scaling_max_freq | tr -d '\r\n')
    export cpu_clk_cpu1_max_format=$(bc <<< "scale=$scale; $cpu_clk_cpu1_max / $pre")
    export cpu_clk_cpu2_max=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu5/cpufreq/scaling_max_freq | tr -d '\r\n')
    export cpu_clk_cpu2_max_format=$(bc <<< "scale=$scale; $cpu_clk_cpu2_max / $pre")
    export cpu_clk_cpu3_max=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu6/cpufreq/scaling_max_freq | tr -d '\r\n')
    export cpu_clk_cpu3_max_format=$(bc <<< "scale=$scale; $cpu_clk_cpu3_max / $pre")

    # Kyro 585 Silver @ 1.80GHz
    export cpu_clk_cpu4_max=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu0/cpufreq/scaling_max_freq | tr -d '\r\n')
    export cpu_clk_cpu4_max_format=$(bc <<< "scale=$scale; $cpu_clk_cpu4_max / $pre")
    export cpu_clk_cpu5_max=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu1/cpufreq/scaling_max_freq | tr -d '\r\n')
    export cpu_clk_cpu5_max_format=$(bc <<< "scale=$scale; $cpu_clk_cpu5_max / $pre")
    export cpu_clk_cpu6_max=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu2/cpufreq/scaling_max_freq | tr -d '\r\n')
    export cpu_clk_cpu6_max_format=$(bc <<< "scale=$scale; $cpu_clk_cpu6_max / $pre")
    export cpu_clk_cpu7_max=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu3/cpufreq/scaling_max_freq | tr -d '\r\n')
    export cpu_clk_cpu7_max_format=$(bc <<< "scale=$scale; $cpu_clk_cpu7_max / $pre")

}

function get_qrb5165_cpu_clk_min() {

    scale=2
    pre=1000000

    # Kyro 585 Prime @ 2.84GHz
    export cpu_clk_cpu0_min=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu7/cpufreq/scaling_min_freq | tr -d '\r\n')
    export cpu_clk_cpu0_min_format=$(bc <<< "scale=$scale; $cpu_clk_cpu0_min / $pre")

    # Kyro 585 Gold @ 2.42GHz
    export cpu_clk_cpu1_min=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu4/cpufreq/scaling_min_freq | tr -d '\r\n')
    export cpu_clk_cpu1_min_format=$(bc <<< "scale=$scale; $cpu_clk_cpu1_min / $pre")
    export cpu_clk_cpu2_min=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu5/cpufreq/scaling_min_freq | tr -d '\r\n')
    export cpu_clk_cpu2_min_format=$(bc <<< "scale=$scale; $cpu_clk_cpu2_min / $pre")
    export cpu_clk_cpu3_min=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu6/cpufreq/scaling_min_freq | tr -d '\r\n')
    export cpu_clk_cpu3_min_format=$(bc <<< "scale=$scale; $cpu_clk_cpu3_min / $pre")

    # Kyro 585 Silver @ 1.80GHz
    export cpu_clk_cpu4_min=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu0/cpufreq/scaling_min_freq | tr -d '\r\n')
    export cpu_clk_cpu4_min_format=$(bc <<< "scale=$scale; $cpu_clk_cpu4_min / $pre")
    export cpu_clk_cpu5_min=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu1/cpufreq/scaling_min_freq | tr -d '\r\n')
    export cpu_clk_cpu5_min_format=$(bc <<< "scale=$scale; $cpu_clk_cpu5_min / $pre")
    export cpu_clk_cpu6_min=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu2/cpufreq/scaling_min_freq | tr -d '\r\n')
    export cpu_clk_cpu6_min_format=$(bc <<< "scale=$scale; $cpu_clk_cpu6_min / $pre")
    export cpu_clk_cpu7_min=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu3/cpufreq/scaling_min_freq | tr -d '\r\n')
    export cpu_clk_cpu7_min_format=$(bc <<< "scale=$scale; $cpu_clk_cpu7_min / $pre")

}

function get_qrb5165_gpu_clk_max() {

    scale=2
    pre=1000000

    export gpu_clk_opengl_core_max=$(adb -s ${DEVICE_SERIAL} shell cat /sys/class/kgsl/kgsl-3d0/max_gpuclk | tr -d '\r\n')
    export gpu_clk_opengl_core_max_format=$(bc <<< "scale=$scale; $gpu_clk_opengl_core_max / $pre")
}

function get_qrb5165_gpu_clk_min() {
    export gpu_clk_opengl_core_min=$(adb -s ${DEVICE_SERIAL} shell cat /sys/class/kgsl/kgsl-3d0/min_clock_mhz | tr -d '\r\n')
}

function get_qrb5165_cpu_clk() {
    scale=2
    pre=1000000

    # Kyro 585 Prime @ 2.84GHz
    export cpu_clk_cpu0=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu7/cpufreq/scaling_cur_freq | tr -d '\r\n')
    export cpu_clk_cpu0_format=$(bc <<< "scale=$scale; $cpu_clk_cpu0 / $pre")

    # Kyro 585 Gold @ 2.42GHz
    export cpu_clk_cpu1=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu4/cpufreq/scaling_cur_freq | tr -d '\r\n')
    export cpu_clk_cpu1_format=$(bc <<< "scale=$scale; $cpu_clk_cpu1 / $pre")
    export cpu_clk_cpu2=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu5/cpufreq/scaling_cur_freq | tr -d '\r\n')
    export cpu_clk_cpu2_format=$(bc <<< "scale=$scale; $cpu_clk_cpu2 / $pre")
    export cpu_clk_cpu3=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu6/cpufreq/scaling_cur_freq | tr -d '\r\n')
    export cpu_clk_cpu3_format=$(bc <<< "scale=$scale; $cpu_clk_cpu3 / $pre")

    # Kyro 585 Silver @ 1.80GHz
    export cpu_clk_cpu4=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu0/cpufreq/scaling_cur_freq | tr -d '\r\n')
    export cpu_clk_cpu4_format=$(bc <<< "scale=$scale; $cpu_clk_cpu4 / $pre")
    export cpu_clk_cpu5=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu1/cpufreq/scaling_cur_freq | tr -d '\r\n')
    export cpu_clk_cpu5_format=$(bc <<< "scale=$scale; $cpu_clk_cpu5 / $pre")
    export cpu_clk_cpu6=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu2/cpufreq/scaling_cur_freq | tr -d '\r\n')
    export cpu_clk_cpu6_format=$(bc <<< "scale=$scale; $cpu_clk_cpu6 / $pre")
    export cpu_clk_cpu7=$(adb -s ${DEVICE_SERIAL} shell cat ${target_cpu_debug_path}/cpu3/cpufreq/scaling_cur_freq | tr -d '\r\n')
    export cpu_clk_cpu7_format=$(bc <<< "scale=$scale; $cpu_clk_cpu7 / $pre")

}

function get_qrb5165_npu_clk() {
    scale=2
    pre=1000000

    # Core
    export npu_core_clk_curr=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/clk/npu_cc_core_clk/clk_measure | tr -d '\r\n')
    export npu_core_clk_curr_format=$(bc <<< "scale=$scale; $npu_cp_clk_curr / $pre")

    # Control Processor
    export npu_cp_clk_curr=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/clk/npu_cc_core_clk/clk_measure | tr -d '\r\n')
    export npu_cp_clk_curr_format=$(bc <<< "scale=$scale; $npu_cp_clk_curr / $pre")
    export npu_cp_clk_vote=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/clk/npu_cc_core_clk/clk_rate | tr -d '\r\n')
    export npu_cp_clk_vote_format=$(bc <<< "scale=$scale; $npu_cp_clk_vote / $pre")

    # Data Plan Engine (DP)
    export npu_dp0_clk_curr=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/clk/npu_cc_cal_hm0_clk/clk_measure | tr -d '\r\n')
    export npu_dp0_clk_curr_format=$(bc <<< "scale=$scale; $npu_dp0_clk_curr / $pre")
    export npu_dp0_clk_vote=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/clk/npu_cc_cal_hm0_clk/clk_rate | tr -d '\r\n')
    export npu_dp0_clk_vote_format=$(bc <<< "scale=$scale; $npu_dp0_clk_vote / $pre")
    export npu_dp1_clk_curr=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/clk/npu_cc_cal_hm1_clk/clk_measure | tr -d '\r\n')
    export npu_dp1_clk_curr_format=$(bc <<< "scale=$scale; $npu_dp1_clk_curr / $pre")
    export npu_dp1_clk_vote=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/clk/npu_cc_cal_hm1_clk/clk_rate | tr -d '\r\n')
    export npu_dp1_clk_vote_format=$(bc <<< "scale=$scale; $npu_dp1_clk_vote / $pre")

    # Power Level
    export npu_power_level=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/npu/pwr_level | tr -d '\r\n')

    # DSP
    export npu_dsp_axi_curr=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/clk/npu_cc_dsp_axi_clk/clk_measure | tr -d '\r\n')
    export npu_dsp_axi_curr_format=$(bc <<< "scale=$scale; $npu_dsp_axi_curr / $pre")
    export npu_dsp_ahbm_curr=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/clk/npu_cc_dsp_ahbm_clk/clk_measure | tr -d '\r\n')
    export npu_dsp_ahbm_curr_format=$(bc <<< "scale=$scale; $npu_dsp_ahbm_curr / $pre")
    export npu_dsp_ahbs_curr=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/clk/npu_cc_dsp_ahbs_clk/clk_measure | tr -d '\r\n')
    export npu_dsp_ahbs_curr_format=$(bc <<< "scale=$scale; $npu_dsp_ahbs_curr / $pre")

    # NoC
    export npu_noc_ahb_curr=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/clk/npu_cc_noc_ahb_clk/clk_measure | tr -d '\r\n')
    export npu_noc_ahb_curr_format=$(bc <<< "scale=$scale; $npu_dsp_axi_curr / $pre")
    export npu_noc_axi_curr=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/clk/npu_cc_noc_axi_clk/clk_measure | tr -d '\r\n')
    export npu_noc_axi_curr_format=$(bc <<< "scale=$scale; $npu_dsp_ahbm_curr / $pre")
    export npu_noc_dma_curr=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/clk/npu_cc_noc_dma_clk/clk_measure | tr -d '\r\n')
    export npu_noc_dma_curr_format=$(bc <<< "scale=$scale; $npu_dsp_ahbs_curr / $pre")
}

function get_qrb5165_cdsp_clk() {

    # sysMonApp

    # SNoC: System Network on Chip
    # BIMC: Bus Integrated Memory Controller
    # MemNoc: Memory Network on Chip

    export cdsp_clk_core='Empty'
    export cdsp_clk_snoc_vote='Empty'
    export cdsp_clk_snoc_curr='Empty'
    export cdsp_clk_memnoc_vote='Empty'
    export cdsp_clk_bimc_curr='Empty'

    lines=$(adb -s ${DEVICE_SERIAL} shell /data/sysMonApp getstate --q6 cdsp)
    while read -r line
    do
        if [[ $line == *"DSP Core clock"* ]]; then
            export cdsp_clk_core=$(echo ${line#*:} | tr -d '\r\n')
        fi
        if [[ $line == *"SNOC Vote"* ]]; then
            export cdsp_clk_snoc_vote_core=$(echo ${line#*:} | tr -d '\r\n')
        fi
        if [[ $line == *"MEMNOC Vote"* ]]; then
            export cdsp_clk_memnoc_vote=$(echo ${line#*:} | tr -d '\r\n')
        fi
        if [[ $line == *"Measured SNOC"* ]]; then
            export cdsp_clk_snoc_curr=$(echo ${line#*:} | tr -d '\r\n')
        fi
        if [[ $line == *"Measured BIMC"* ]]; then
            export cdsp_clk_bimc_curr=$(echo ${line#*:} | tr -d '\r\n')
        fi

    done <<< "$lines"

    now=$(date '+%d-%m-%y %T')

    # /data/local/tmp/sysMonApp getPowerStats --q6 cdsp && sleep 300 && /data/local/tmp/sysMonApp getPowerStats --q6 cdsp &
}

function get_qrb5165_gpu_clk() {
    scale=2
    pre=1000000

    export gpu_clk_opengl_core_curr=$(adb -s ${DEVICE_SERIAL} shell cat /sys/kernel/debug/clk/measure_only_gpu_cc_gx_gfx3d_clk/clk_measure | tr -d '\r\n')
    export gpu_clk_opengl_core_curr_format=$(bc <<< "scale=$scale; $gpu_clk_opengl_core_curr / $pre")
    # echo $gpu_clk_opengl_core_curr

}

function get_disk_usage() {
    export disk_root_size=$(adb -s ${DEVICE_SERIAL} shell echo '$(df -h --output=size /)' | tr -d 'Size ' | tr -d '\r\n')
    export disk_root_used=$(adb -s ${DEVICE_SERIAL} shell echo '$(df -h --output=used /)' | tr -d 'Used ' | tr -d '\r\n')
    export disk_root_avaliable=$(adb -s ${DEVICE_SERIAL} shell echo '$(df -h --output=avail /) '| tr -d 'Avail ' | tr -d '\r\n')
    export disk_root_usage=$(adb -s ${DEVICE_SERIAL} shell echo '$(df --output=pcent /)' | tr -d 'Use% ' | tr -d '\r\n')
}

function get_system_info() {
    export os_description=$(adb -s ${DEVICE_SERIAL} shell lsb_release -d | tr -d 'Description:	' | tr -d '\r\n')
    export kernel_version=$(adb -s ${DEVICE_SERIAL} shell uname -r | tr -d '\r\n')
}

function get_network_info() {
    export hostname_ip=$(adb -s ${DEVICE_SERIAL} shell ifconfig eth0 | grep "inet " | awk '{print $2}' | tr -d '\r\n')
    export hostname=$(adb -s ${DEVICE_SERIAL} shell hostname | tr -d '\r\n')
    export iw_ssid=$(adb -s ${DEVICE_SERIAL} shell iwgetid -r | tr -d '\r\n')
}

function get_top_process() {
    lvar=$1
    top_process_result=$(adb -s ${DEVICE_SERIAL} shell ps ax -o pid,rss,pcpu,ucmd --sort=-cpu,-rss | sed -n "$lvar,$lvar p" | awk '{printf "%s: %sM:  %s%%" , $4, $2/1024, $3 }' | tr -d '\r\n')
    echo "$top_process_result"
}

function get_logcat_last_lines() {
    lines=5
    adb -s ${DEVICE_SERIAL} logcat -t $lines | tail -n +2 > /tmp/sample_qtop_adb.log
}

init

main() {
    get_adb_devices
    get_qrb5165_cpu_clk
    get_qrb5165_cdsp_clk
    get_qrb5165_npu_clk
    get_qrb5165_gpu_clk
    get_disk_usage
    get_network_info
    get_logcat_last_lines
    get_minidm_logs

    window "System Information" "green" "22%"
        append_tabbed "TIME,$(date '+%Y/%m/%d %T')" 2 ',' "yellow"
        addsep
        append_tabbed "ADB Serial,$DEVICE_SERIAL" 2 ','
        append_tabbed "Operating System:$os_description" 2
        append_tabbed "Linux Kernel:$kernel_version" 2
    endwin

    window "Connected ADB Devices" "green" "22%"
        append_file /tmp/sample_qtop_adb_devices.log
    endwin

    window "Connected Mini-dm Devices" "green" "22%"
        append_file /tmp/sample_qtop_minidm_devices.log
        append "First Port is $minidm_first_usbport" "left" "yellow"
        addsep
        append "mini-dm status" "center" "green"
        addsep
        append_file /tmp/sample_qtop_minidm_status.log
    endwin

    window "Top 5 Process" "green" "22%"
        for i in `seq 2 6`; do
            append_tabbed "$(($i-2)) $(get_top_process $i | tr -d '\r\n')" 3
        done
    endwin

    window "Network" "green" "14%"
        append_tabbed "IP:$hostname_ip" 2
        append_tabbed "Hostname:$hostname" 2
        append_tabbed "WIFI SSID:$iw_ssid" 2
        append_tabbed "WIFI RSSI:" 2
    endwin

    col_right
    window "Disk Usage" "green" "8%"
        append_tabbed "Size:$disk_root_size" 2
        append_tabbed "Used:$disk_root_used" 2
        append_tabbed "Avaliable:$disk_root_avaliable" 2
        vumeter "$disk_root_usage%" 9 $disk_root_usage 100 "green" "red" "white"
    endwin

    col_right
    move_up

    window "CPU (Kyro585)" "green" "33%"
        append_tabbed ":Current:Min:Max" 4 ':' "white"
        append_tabbed "Prime  0:$cpu_clk_cpu0_format GHz:$cpu_clk_cpu0_min_format GHz:$cpu_clk_cpu0_max_format GHz" 4 ':' "red"
        append_tabbed "Gold   0:$cpu_clk_cpu1_format GHz:$cpu_clk_cpu1_min_format GHz:$cpu_clk_cpu1_max_format GHz" 4 ':' "yellow"
        append_tabbed "Gold   1:$cpu_clk_cpu2_format GHz:$cpu_clk_cpu2_min_format GHz:$cpu_clk_cpu2_max_format GHz" 4 ':' "yellow"
        append_tabbed "Gold   2:$cpu_clk_cpu3_format GHz:$cpu_clk_cpu3_min_format GHz:$cpu_clk_cpu3_max_format GHz" 4 ':' "yellow"
        append_tabbed "Silver 0:$cpu_clk_cpu4_format GHz:$cpu_clk_cpu4_min_format GHz:$cpu_clk_cpu4_max_format GHz" 4 ':' "cyan"
        append_tabbed "Silver 1:$cpu_clk_cpu5_format GHz:$cpu_clk_cpu5_min_format GHz:$cpu_clk_cpu5_max_format GHz" 4 ':' "cyan"
        append_tabbed "Silver 2:$cpu_clk_cpu6_format GHz:$cpu_clk_cpu6_min_format GHz:$cpu_clk_cpu6_max_format GHz" 4 ':' "cyan"
        append_tabbed "Silver 3:$cpu_clk_cpu7_format GHz:$cpu_clk_cpu7_min_format GHz:$cpu_clk_cpu7_max_format GHz" 4 ':' "cyan"
        addsep
        append "GPU (Adreno 650)" "center" "green"
        append_tabbed ":Current:Min:Max" 4 ':' "white"
        append_tabbed "GPU:$gpu_clk_opengl_core_curr_format MHz:$gpu_clk_opengl_core_min MHz:$gpu_clk_opengl_core_max_format MHz" 4 ':' "yellow"
        addsep
        append "Hexagon 698 DSP (V66 cDSP)" "center" "green"
        addsep
        append_tabbed "Core Current:SNOC Current:BIMC Current:SNoC Voted:MEMNOC Voted" 5 ':' "white"
        append_tabbed "$cdsp_clk_core:$cdsp_clk_snoc_curr:$cdsp_clk_bimc_curr:$cdsp_clk_snoc_vote_core:$cdsp_clk_memnoc_vote" 5 ':' "yellow"
        addsep
        append "NPU (HTA230)" "center" "green"
        addsep
        append_tabbed ":Current:Voted" 3 ':' "white"
        append_tabbed "Control Processor:$npu_cp_clk_curr_format Hz:$npu_cp_clk_vote_format Hz" 3 ':' "yellow"
        append_tabbed "DATA PLAN 0:$npu_dp0_clk_curr_format MHz:$npu_dp0_clk_vote_format MHz" 3 ':' "yellow"
        append_tabbed "DATA PLAN 1:$npu_dp1_clk_curr_format MHz:$npu_dp1_clk_vote_format MHz" 3 ':' "yellow"

        append_tabbed "DSP Bus:AXI:AHBM:AHBS" 4
        append_tabbed ":$npu_dsp_axi_curr_format MHz:$npu_dsp_ahbm_curr_format MHz:$npu_dsp_ahbs_curr_format MHz" 4 ':' "yellow"
        append_tabbed "NoC Bus:AXI:AHB:DMA" 4
        append_tabbed ":$npu_noc_axi_curr_format MHz:$npu_noc_ahb_curr_format MHz:$npu_noc_dma_curr_format MHz" 4 ':' "yellow"
    endwin

    window "GPU Frequency Meter" "green" "33%"
        vumeter "GPU $gpu_clk_opengl_core_curr_format MHz" 39 $gpu_clk_opengl_core_curr $gpu_clk_opengl_core_max "green" "red" "white"
        addsep
        append "NPU Frequency Meter" "center" "green"
        addsep
        vumeter "DP0 $npu_dp0_clk_curr_format MHz" 50 $npu_dp0_clk_curr 1000000000 "green" "red" "white"
        vumeter "DP1 $npu_dp1_clk_curr_format MHz" 50 $npu_dp1_clk_curr 1000000000 "green" "red" "white"
    endwin

    window "CPU Big Freq. Meter" "green" "17%"
        vumeter "P0 $cpu_clk_cpu0_format GHz" 20 $cpu_clk_cpu0 $cpu_clk_cpu0_max "green" "red" "white"
        vumeter "G0 $cpu_clk_cpu1_format GHz" 20 $cpu_clk_cpu1 $cpu_clk_cpu1_max "green" "red" "white"
        vumeter "G1 $cpu_clk_cpu2_format GHz" 20 $cpu_clk_cpu2 $cpu_clk_cpu2_max "green" "red" "white"
        vumeter "G2 $cpu_clk_cpu3_format GHz" 20 $cpu_clk_cpu3 $cpu_clk_cpu3_max "green" "red" "white"
    endwin

    col_right
    window "CPU Little Freq. Meter" "green" "16%"
        vumeter "S0 $cpu_clk_cpu4_format GHz" 18 $cpu_clk_cpu4 $cpu_clk_cpu4_max "green" "red" "white"
        vumeter "S1 $cpu_clk_cpu5_format GHz" 18 $cpu_clk_cpu5 $cpu_clk_cpu5_max "green" "red" "white"
        vumeter "S2 $cpu_clk_cpu6_format GHz" 18 $cpu_clk_cpu6 $cpu_clk_cpu6_max "green" "red" "white"
        vumeter "S3 $cpu_clk_cpu7_format GHz" 18 $cpu_clk_cpu7 $cpu_clk_cpu7_max "green" "red" "white"
    endwin

    col_right
    move_up

    window "Logcat" "green" "45%"
        append_file /tmp/sample_qtop_adb.log
    endwin

    window "Minidm [/tmp/sample_qtop_minidm_log_lines]" "green" "45%"
        append_file /tmp/sample_qtop_minidm_log_lines.log
    endwin
    
}

main_loop -t 0.001
